function signal = encode_standard(fs, duration, f)
window = fs * duration;

%% 4QAM星座图
QAM_11 = QAM_mod_standard(1, 1, fs, duration, f);
QAM_1n1 = QAM_mod_standard(1, -1, fs, duration, f);
QAM_n11 = QAM_mod_standard(-1, 1, fs, duration, f);
QAM_n1n1 = QAM_mod_standard(-1, -1, fs, duration, f);
signal = [QAM_11, QAM_11, QAM_11, ... 
            QAM_1n1, QAM_1n1, QAM_1n1, ... 
            QAM_n11, QAM_n11, QAM_n11, ... 
            QAM_n1n1, QAM_n1n1, QAM_n1n1];

% %% 16QAM星座图
% QAM_33 = QAM_mod_standard(3, 3, fs, duration, f);
% QAM_31 = QAM_mod_standard(3, 1, fs, duration, f);
% QAM_3n1 = QAM_mod_standard(3, -1, fs, duration, f);
% QAM_3n3 = QAM_mod_standard(3, -3, fs, duration, f);
% QAM_13 = QAM_mod_standard(1, 3, fs, duration, f);
% QAM_11 = QAM_mod_standard(1, 1, fs, duration, f);
% QAM_1n1 = QAM_mod_standard(1, -1, fs, duration, f);
% QAM_1n3 = QAM_mod_standard(1, -3, fs, duration, f);
% QAM_n13 = QAM_mod_standard(-1, 3, fs, duration, f);
% QAM_n11 = QAM_mod_standard(-1, 1, fs, duration, f);
% QAM_n1n1 = QAM_mod_standard(-1, -1, fs, duration, f);
% QAM_n1n3 = QAM_mod_standard(-1, -3, fs, duration, f);
% QAM_n33 = QAM_mod_standard(-3, 3, fs, duration, f);
% QAM_n31 = QAM_mod_standard(-3, 1, fs, duration, f);
% QAM_n3n1 = QAM_mod_standard(-3, -1, fs, duration, f);
% QAM_n3n3 = QAM_mod_standard(-3, -3, fs, duration, f);
% 
% signal = [zeros(1, window), QAM_33, QAM_33, QAM_33, ... 
%             zeros(1, window), QAM_31, QAM_31, QAM_31, ... 
%             zeros(1, window), QAM_3n1, QAM_3n1, QAM_3n1, ... 
%             zeros(1, window), QAM_3n3, QAM_3n3, QAM_3n3, ... 
%             zeros(1, window), QAM_11, QAM_11, QAM_11, ... 
%             zeros(1, window), QAM_13, QAM_13, QAM_13, ... 
%             zeros(1, window), QAM_1n1, QAM_1n1, QAM_1n1, ... 
%             zeros(1, window), QAM_1n3, QAM_1n3, QAM_1n3, ... 
%             zeros(1, window), QAM_n13, QAM_n13, QAM_n13, ... 
%             zeros(1, window), QAM_n11, QAM_n11, QAM_n11, ... 
%             zeros(1, window), QAM_n1n1, QAM_n1n1, QAM_n1n1, ... 
%             zeros(1, window), QAM_n1n3, QAM_n1n3, QAM_n1n3, ... 
%             zeros(1, window), QAM_n33, QAM_n33, QAM_n33, ... 
%             zeros(1, window), QAM_n31, QAM_n31, QAM_n31, ... 
%             zeros(1, window), QAM_n3n1, QAM_n3n1, QAM_n3n1, ... 
%             zeros(1, window), QAM_n3n3, QAM_n3n3, QAM_n3n3];
end